/* 
 * File:   fat16.h
 * Author: Luke
 *
 * Created on 30. October 2017, 21:59
 */

#ifndef FAT16_H
#define	FAT16_H

#define FBR_OEM_IDENTIFIER "MSDOS5.0"
#define FBR_BYTES_PER_SECTOR 512
#define FBR_SECTORS_PER_CLUSTER 1
#define FBR_RESERVED_SECTORS 1
#define FBR_NUMBER_OF_FATS 1
#define FBR_ROOT_ENTRIES 16
#define FBR_NUMBER_OF_SECTORS 4095
#define FBR_MEDIA_DESCRIPTOR 0XF8
#define FBR_SECTORS_PER_FAT 1
#define FBR_SECTORS_PER_HEAD 63
#define FBR_HEADS_PER_CYLINDER 16
#define FBR_HIDDEN_SECTORS 0 /* OR 1? */
#define FBR_EXT_FLAGS 0b00000001
#define FBR_ROOT_DIRECTORY_START 2
#define FBR_SIGNATURE 0X55AA

#define MRB_PARTITION_STATUS 0x80
#define MBR_PARTITION_TYPE 4
#define MBR_FIRST_PARTITION_SECTOR 1
#define MBR_PARTITION_SIZE 4095
#define MBR_PARTITION_START_CYLINDER (MBR_FIRST_PARTITION_SECTOR/(FBR_HEADS_PER_CYLINDER*FBR_SECTORS_PER_HEAD))
#define MBR_PARTITION_START_HEAD ((MBR_FIRST_PARTITION_SECTOR/FBR_SECTORS_PER_HEAD)%FBR_HEADS_PER_CYLINDER)
#define MBR_PARTITION_START_SECTOR ((MBR_FIRST_PARTITION_SECTOR%FBR_SECTORS_PER_HEAD)+1)
#define MBR_LAST_PARTITION_SECTOR (MBR_FIRST_PARTITION_SECTOR+MBR_PARTITION_SIZE-1)
#define MBR_PARTITION_END_CYLINDER (MBR_LAST_PARTITION_SECTOR/(FBR_HEADS_PER_CYLINDER*FBR_SECTORS_PER_HEAD))
#define MBR_PARTITION_END_HEAD ((MBR_LAST_PARTITION_SECTOR/FBR_SECTORS_PER_HEAD)%FBR_HEADS_PER_CYLINDER)
#define MBR_PARTITION_END_SECTOR ((MBR_LAST_PARTITION_SECTOR%FBR_SECTORS_PER_HEAD)+1)
#define MBR_SIGNATURE 0X55AA



#define ROOT_DRIVE_NAME "SolarChargr"
#define ROOT_FILE_NAME "FILE    "
#define ROOT_FILE_EXTENSION "TXT"
#define ROOT_FILE_CONTENT "Hello World!"
#define ROOT_FILE_SIZE 12
#define ROOT_FILE_FIRST_CLUSTER 2


void fat_format_flash(void);

#endif	/* FAT16_H */

